version: "3.8"

services:
  mysql:
    build: ./SQL
    container_name: mysql_container
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - escape_network

  api:
    build: ./API
    container_name: flask_api_container
    restart: always
    depends_on:
      - mysql
    env_file:
      - .env
    ports:
      - "5000:5000"
    networks:
      - escape_network

  web:
    build: ./WEB
    container_name: angular_web_container
    restart: always
    depends_on:
      - api
    environment:
      API_URL: http://192.168.0.33:5000/api
    ports:
      - "80:80"
    networks:
      - escape_network

volumes:
  mysql_data:

networks:
  escape_network:
    driver: bridge
